spring.application.name=ECOHARMONY_PARK_BACK

# Configuración de SQLite
spring.datasource.url=jdbc:sqlite:ecoharmony_park.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Ejecutar ResetBD.sql después de crear las tablas
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:ResetBD.sql
spring.jpa.defer-datasource-initialization=true